export const coursesData = [
    {
        slug: "essence-of-calculus",
        title: "Essence of Calculus",
        teacherName: "Grant Sanderson",
        rating: 5,
        raterCount: 3_000_500,
        tags: "Math",
        imageUrl: "/essence-of-calculus.jpg",
    },
    {
        slug: "but-what-is-a-fourier-transform-a-visual-introduction",
        title: "But What is a Fourier Transform? A Visual Introduction.",
        teacherName: "Grant Sanderson",
        rating: 4.7,
        raterCount: 2_500_037,
        tags: "Math,Science",
        imageUrl: "/fourier-transform.jpg",
    },
    {
        slug: "the-future-of-reasoning",
        title: "The Future of Reasoning",
        teacherName: "Michael Stevens",
        rating: 4.7,
        raterCount: 2_000_310,
        tags: "Science,Philosophy",
        imageUrl: "/future-of-reasoning.jpg",
    },
    {
        slug: "the-anatomy-of-dolphins",
        title: "The Anatomy of Dolphins",
        teacherName: "Jotaro Kujo",
        rating: 4.5,
        raterCount: 513_473,
        tags: "Science,Animal,Biology",
        imageUrl: "/dolphin.jpg",
    },
    {
        slug: "free-your-voice-vocal-training",
        title: "Free Your Voice: Vocal Training",
        teacherName: "Chris Liepe",
        rating: 4,
        raterCount: 450_021,
        tags: "Music,Vocal",
        imageUrl: "/free-your-voice.png",
    },
    {
        slug: "database-management",
        title: "Database Management",
        teacherName: "Pahril Dwi Saputra",
        rating: 4.7,
        raterCount: 250_030,
        tags: "Programming,Software Development",
        imageUrl: "/dbm.jpg",
    },
    {
        slug: "learn-by-rediscovery",
        title: "Learn By Rediscovery",
        teacherName: "Ilham Al Basith",
        rating: 3.7,
        raterCount: 7_237,
        tags: "Programming",
        imageUrl: "/rediscovery.jpg",
    },
    {
        slug: "php-basic",
        title: "PHP Basic",
        teacherName: "John Doe",
        rating: 2.3,
        raterCount: 1_500,
        tags: "Programming,PHP,Web",
        imageUrl: "/php.png",
    },
];
